### ISSUE TITLE
Dapp 注册不成功

### ISSUE THREAD

**Issue by houruixiang** [brant9527/asch-test#1]
按照流程做，返回的ID是
0d9cecfaad6f8bb1f942ddf9c1fa1e0cd4dc49037632703d104d07a8681e610a，
但是我输入：
http://localhost:4096/api/dapps/get?id=676efadb53749e38f36dc3a614397f05c1fd37d8049f64ed2d2eb3e089efeba3
给出
{"success":false,"error":"DApp not found"}
好奇怪。

再次输入http://localhost:4096/api/dapps查询APP ID
给出
{"success":true,"dapps":[],"count":{"count":0}}

这个压根没有注册成功也是醉了，
请问大佬怎么解决

**Comment by brant9527** [comment]
你注意一下，你发布的dappid是否有弄错。他之前有个步骤的id是你生成的一个id。看下是不是你id填错了的原因

**Comment by houruixiang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
步骤的id是你生成的一个id，这个id必须是我五个委托人的ID吗，我是重新运行命令 asch-cli crypto -g 然后生成一个新的账号，但是我忽略这个账号应该是我的主账号，所以我搞错了，生成的APPID和用户不对应，这样才搞到现在。谢谢你的提醒。

，four angry men<notifications@github.com> 写道： 


你注意一下，你发布的dappid是否有弄错。他之前有个步骤的id是你生成的一个id。看下是不是你id填错了的原因
